---
platform: linux
image: docker:///starkandwayne/postgresql-docker-pivotal-pipeline

inputs:
- name: tile
- name: cf-subway-boshrelease
  path: tile/tmp/releases/cf-subway-boshrelease
- name: docker-boshrelease
  path: tile/tmp/releases/docker-boshrelease
- name: postgresql-docker-boshrelease
  path: tile/tmp/releases/postgresql-docker-boshrelease

run:
  path: tile/ci/tasks/generate-product.sh
