---
platform: linux
image: docker:///dingotiles/dingo-postgresql-pivotaltile-pipeline

inputs:
- name: tile
- name: tile-version
- name: patroni-docker
- name: broker-registrar
- name: etcd
- name: remote-syslog

outputs:
- name: product

run:
  path: tile/ci/tasks/generate-product.sh
