---
platform: linux
image: docker:///starkandwayne/postgresql-docker-pivotal-pipeline

inputs:
- name: tile
- name: cf-subway-boshrelease
- name: docker-boshrelease
- name: postgresql-docker-boshrelease

run:
  path: tile/ci/tasks/generate-product.sh
