---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-pivotaltile-pipeline}

inputs:
- name: tile
- name: tile-version
- name: dingo-postgresql
- name: broker-registrar
- name: pivnet-stemcell

outputs:
- name: product

run:
  path: tile/ci/tasks/generate-product.sh
