---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-pivotaltile-pipeline}


inputs:
- name: tile
- name: tile-version

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: ap-southeast-1
  from_bucket:
  to_bucket:

run:
  path: tile/ci/tasks/promote-public.sh
