---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-pivotaltile-pipeline}


inputs:
- name: tile
- name: generated-tile

params:
  opsmgr_url:
  opsmgr_skip_ssl_verification:
  opsmgr_username:
  opsmgr_password:
  opsmgr_version:

run:
  path: tile/ci/tasks/upload-product.sh
