jobs:
- name: create-product
  plan:
  - aggregate:
    - get: tile
      trigger: false
    - get: product-tile
      trigger: true
    - get: docker-boshrelease
      trigger: true
      params:
        tarball: true
    - get: postgresql-docker-boshrelease
      trigger: true
      params:
        tarball: true
  - task: generate-product
    file: tile/ci/tasks/generate-product.yml
  - put: generated-tile
    params:
      from: generate-product/tile/postgresql-docker.pivotal

- name: upload-product
  plan:
  - aggregate:
    - get: tile
    - get: generated-tile
      passed: [create-product]
  - task: upload-product
    file: tile/ci/tasks/upload-product.yml
    config:
      params:
        opsmgr_url: {{opsmgr-url}}
        opsmgr_skip_ssl_verification: {{opsmgr-skip-ssl-verification}}
        opsmgr_username: {{opsmgr-username}}
        opsmgr_password: {{opsmgr-password}}

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: docker-image-tile
    trigger: true
  - put: docker-image
    params:
      build: tile-docker-image/ci/ci_image

resources:
- name: tile
  type: git
  source:
    uri: git@github.com:drnic/postgresql-docker-pivotal.git
    branch: master
    private_key: {{github-key}}
- name: product-tile
  type: git
  source:
    uri: git@github.com:drnic/postgresql-docker-pivotal.git
    branch: master
    private_key: {{github-key}}
    paths: [metadata, content_migrations]
- name: docker-image-tile
  type: git
  source:
    uri: git@github.com:drnic/postgresql-docker-pivotal.git
    branch: master
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-hub-task-image}}

- name: docker-boshrelease
  type: bosh-io-release
  source:
    repository: cf-platform-eng/docker-boshrelease
- name: postgresql-docker-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/postgresql-docker-boshrelease
- name: generated-tile
  type: s3
  source:
    versioned_file: postgresql-docker.pivotal
    access_key_id: {{concourse-artifacts-access-key}}
    secret_access_key: {{concourse-artifacts-secret-access-key}}
    bucket: {{pivotal-files-bucket}}
