jobs:
- name: create-product
  plan:
  - get: tile
    trigger: true
  # - task: generate-example-product
  #   privileged: true
  #   file: ops-manager-example/ci/tasks/generate-example-product.yml
  #   config:
  #     params:
  #       REPO_DIR: ops-manager-example
  # - put: generated-example-product
  #   params:
  #     from: ops-manager-example/example-product/generated-example-product.pivotal

resources:
- name: tile
  type: git
  source:
    private_key: {{github-key}}
    branch: master
    uri: git@github.com:drnic/postgresql-docker-pivotal.git
# - name: generated-tile
#   type: s3
#   source:
#     versioned_file: postgresql-docker.pivotal
#     access_key_id: {{concourse-artifacts-access-key}}
#     secret_access_key: {{concourse-artifacts-secret-access-key}}
#     bucket: {{pivotal-files-bucket}}
