jobs:
- name: create-product
  plan:
  - aggregate:
    - get: tile
      trigger: true
    - get: docker-boshrelease
      trigger: true
      params:
        tarball: true
    - get: postgresql-docker-boshrelease
      trigger: true
      params:
        tarball: true
  - task: generate-product
    file: tile/ci/tasks/generate-product.yml
  - put: generated-tile
    params:
      from: generate-product/tile/postgresql-docker.pivotal

resources:
- name: tile
  type: git
  source:
    private_key: {{github-key}}
    branch: master
    uri: git@github.com:drnic/postgresql-docker-pivotal.git
- name: docker-boshrelease
  type: bosh-io-release
  source:
    repository: cf-platform-eng/docker-boshrelease
- name: postgresql-docker-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/postgresql-docker-boshrelease
- name: generated-tile
  type: s3
  source:
    versioned_file: postgresql-docker.pivotal
    access_key_id: {{concourse-artifacts-access-key}}
    secret_access_key: {{concourse-artifacts-secret-access-key}}
    bucket: {{pivotal-files-bucket}}
