---
groups:
- name: pipeline
  jobs:
  - create-product
  - upload-opsmgr16
- name: image
  jobs:
  - build-task-image

jobs:
- name: create-product
  serial_groups: [opsmgr17]
  plan:
  - aggregate:
    - get: tile
    - get: product-tile
      trigger: true
    - get: dingo-postgresql
      trigger: true
      params: {tarball: true}
    - get: broker-registrar
      params: {tarball: true}
    - get: tile-version
      params: {pre: rc}
  - task: generate-product
    file: tile/ci/tasks/generate-product.yml
    params:
      AWS_ACCESS_KEY: {{concourse-aws-access-key}}
      AWS_SECRET_KEY: {{concourse-aws-secret-access-key}}
  - put: generated-tile
    params: {file: product/dingo-postgresql-*.pivotal}
  - put: tile-version
    params: {file: tile-version/number}
  - task: upload-product-opsmgr17
    file: tile/ci/tasks/upload-product.yml
    params:
      opsmgr_url: {{opsmgr17-url}}
      opsmgr_skip_ssl_verification: {{opsmgr17-skip-ssl-verification}}
      opsmgr_username: {{opsmgr17-username}}
      opsmgr_password: {{opsmgr17-password}}
      opsmgr_version: 1.7

- name: upload-opsmgr16
  serial_groups: [opsmgr16]
  plan:
  - aggregate:
    - { get: tile }
    - { get: generated-tile, passed: [create-product], trigger: true }
    - { get: tile-version, passed: [create-product] }
  - task: upload-product-opsmgr16
    file: tile/ci/tasks/upload-product.yml
    params:
      opsmgr_url: {{opsmgr16-url}}
      opsmgr_skip_ssl_verification: {{opsmgr16-skip-ssl-verification}}
      opsmgr_username: {{opsmgr16-username}}
      opsmgr_password: {{opsmgr16-password}}
      opsmgr_version: 1.6

- name: bump-patch
  serial_groups: [opsmgr]
  plan:
  - aggregate:
    - get: tile
    - get: tile-version
      passed: [create-product]
      params: {bump: patch}
    - get: generated-tile
      passed: [create-product]
  - task: re-version-product
    file: tile/ci/tasks/re-version-product.yml
    params:
      AWS_ACCESS_KEY: {{concourse-aws-access-key}}
      AWS_SECRET_KEY: {{concourse-aws-secret-access-key}}
  - put: tile-version
    params: {file: tile-version/number}
  - put: generated-tile
    params: {file: reversioned-product/dingo-postgresql-*.pivotal}
  - task: upload-product
    file: tile/ci/tasks/upload-product.yml
    params:
      opsmgr_url: {{opsmgr16-url}}
      opsmgr_skip_ssl_verification: {{opsmgr16-skip-ssl-verification}}
      opsmgr_username: {{opsmgr16-username}}
      opsmgr_password: {{opsmgr16-password}}

- name: bump-minor
  serial_groups: [opsmgr]
  plan:
  - aggregate:
    - get: tile
    - get: tile-version
      passed: [create-product]
      params: {bump: minor}
    - get: generated-tile
      passed: [create-product]
  - task: re-version-product
    file: tile/ci/tasks/re-version-product.yml
    params:
      AWS_ACCESS_KEY: {{concourse-aws-access-key}}
      AWS_SECRET_KEY: {{concourse-aws-secret-access-key}}
  - put: tile-version
    params: {file: tile-version/number}
  - put: generated-tile
    params: {file: reversioned-product/dingo-postgresql-*.pivotal}
  - task: upload-product
    file: tile/ci/tasks/upload-product.yml
    params:
      opsmgr_url: {{opsmgr16-url}}
      opsmgr_skip_ssl_verification: {{opsmgr16-skip-ssl-verification}}
      opsmgr_username: {{opsmgr16-username}}
      opsmgr_password: {{opsmgr16-password}}

- name: promote-patch
  plan:
  - aggregate:
    - get: tile
    - get: tile-version
      passed: [bump-patch]
  - task: promote-public
    file: tile/ci/tasks/promote-public.yml
    params:
      AWS_ACCESS_KEY_ID: {{concourse-aws-access-key}}
      AWS_SECRET_ACCESS_KEY: {{concourse-aws-secret-access-key}}
      AWS_DEFAULT_REGION: ap-southeast-1
      from_bucket: dingo-postgresql-pivotaltile
      to_bucket: dingo-postgresql-public-pivotaltile

- name: promote-minor
  plan:
  - aggregate:
    - get: tile
    - get: tile-version
      passed: [bump-minor]
  - task: promote-public
    file: tile/ci/tasks/promote-public.yml
    params:
      AWS_ACCESS_KEY_ID: {{concourse-aws-access-key}}
      AWS_SECRET_ACCESS_KEY: {{concourse-aws-secret-access-key}}
      AWS_DEFAULT_REGION: ap-southeast-1
      from_bucket: dingo-postgresql-pivotaltile
      to_bucket: dingo-postgresql-public-pivotaltile


- name: build-task-image
  serial: true
  plan:
  - get: docker-image-tile
    trigger: true
  - put: docker-image
    params:
      build: docker-image-tile/ci/ci_image

resources:
- name: tile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-pivotaltile.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
- name: product-tile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-pivotaltile.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
    paths: [templates]
- name: docker-image-tile
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-pivotaltile.git
    branch: {{tile-branch}}
    private_key: {{github-key}}
    paths: [ci/ci_image/*]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql-pivotaltile-pipeline

- name: tile-version
  type: semver
  source:
    driver: git
    uri: git@github.com:dingotiles/dingo-postgresql-pivotaltile.git
    branch: version
    file: version
    initial_version: 0.0.1
    private_key: {{github-key}}

- name: dingo-postgresql
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    user: dingotiles
    repository: dingo-postgresql-release
- name: broker-registrar
  type: bosh-io-release
  source: {repository: cloudfoundry-community/broker-registrar-boshrelease}
- name: etcd
  type: bosh-io-release
  source: {repository: cloudfoundry-incubator/etcd-release}
- name: simple-remote-syslog
  type: bosh-io-release
  source: {repository: cloudfoundry-community/simple-remote-syslog-boshrelease}

- name: generated-tile
  type: s3
  source:
    access_key_id: {{concourse-aws-access-key}}
    secret_access_key: {{concourse-aws-secret-access-key}}
    bucket: dingo-postgresql-pivotaltile
    regexp: dingo-postgresql-(.*).pivotal
    region_name: ap-southeast-1
